version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    command:  mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: seller_tribe
    ports:
      - '4306:3306'
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/init.sh:/docker-entrypoint-initdb.d/init.sh
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/seller_tribe
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/seller_tribe
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database